spring:
  application:
    name: flyway
  profiles:
    default: local

server:
  port: 8099

  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0